services:
  backend:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: "sqlite:////data/coma2.db"
    volumes:
      - backend-data:/data
    ports:
      - 5055:5055
    networks:
      - internal

volumes:
  backend-data:


networks:
  internal:
